# -*- coding: utf-8 -*-
"""ai_project_image_classifier.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSoXK641RUAF4cLbRs4Q5xviTjHbvJ7Z
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files


model = tf.keras.applications.MobileNetV2(weights='imagenet')


def preprocess_image(image_path):
    image = load_img(image_path, target_size=(224, 224))
    image = img_to_array(image)
    image = np.expand_dims(image, axis=0)
    image = tf.keras.applications.mobilenet_v2.preprocess_input(image)
    return image


def classify_image(image_path):
    image = preprocess_image(image_path)
    predictions = model.predict(image)
    decoded_predictions = tf.keras.applications.mobilenet_v2.decode_predictions(predictions, top=1)[0]
    return decoded_predictions


def display_image_with_prediction(image_path, decoded_predictions):
    img = load_img(image_path)
    plt.imshow(img)
    plt.title(f"Prediction: {decoded_predictions[0][1]} ({decoded_predictions[0][2]*100:.2f}%)")
    plt.axis('off')
    plt.show()


print("Please upload image files:")
uploaded_files = files.upload()


for image_name in uploaded_files.keys():
    print(f"\nClassifying: {image_name}")
    decoded_predictions = classify_image(image_name)
    display_image_with_prediction(image_name, decoded_predictions)